#!/bin/bash
source environment
game="$1"
checkpoint="$2"
numSteps="${3:-100}"
echo "game: $game, checkpoint: $checkpoint, numSteps: $numSteps"
rm -rf "agent_viz/$game/rainbow"
python -m dopamine.utils.example_viz --agent=rainbow --game="$game" --num_steps=$numSteps --root_dir=. --restore_checkpoint="./models/rainbow/$game/checkpoints/tf_ckpt-$checkpoint"
